font=Space Mono
font-size=22
dpi-aware=auto
#use-bold=yes
prompt="Menu > "
image-size-ratio=1.0
line-height=29
line-width=500

[colors]
background=2f2f2fff
text=fffffff0
prompt=fffffff0
selection=6E56AFf0
selection-text=fffffff0
input=fffffff0
match=73D216f0
selection-match=73D216f0
border=7fc8fff0

[border]
width=3
radius=8
